version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: praeitor/kittygram_backend:latest
    container_name: backend
    env_file: .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - static:/app/static
      - media:/app/media
  
  frontend:
    image: praeitor/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/app/build/static
  
  gateway:
    image: praeitor/kittygram_gateway:latest
    container_name: gateway
    env_file: .env
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media