version: '3.8'

services:
  gateway:
    build:
      context: ./nginx
    container_name: gateway
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - static:/app/build
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  static:
  media:
  pg_data: